# Базовые настройки
[settings]
smells = true

# Исключаемые пути
[exclude]
paths = [
  "chat_vue/dist/",
  "chat_vue/node_modules/",
  "chat_sys/venv/",
  "chat_sys/.venv/",
  "chat_sys/staticfiles/",
  "**/tests/",
  "**/__tests__/",
  "chat_sys/migrations/"
]

# Плагины для анализа
[[analyzer]]
name = "eslint"
enabled = true
directory = "chat_vue"

[[analyzer]]
name = "ruff"
enabled = true
directory = "chat_sys"