name: Qlty Analysis

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  qlty:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qlty CLI
        # Скачиваем и устанавливаем CLI прямо в раннере
        run: curl https://qlty.sh/install.sh | sh

      - name: Run Qlty analysis
        # Запускаем анализ. 
        # Флаг --fail-on-issues можно добавить, если хотите, чтобы пайплайн падал при ошибках
        run: qlty check
